#echo -n "12345" | base64 
apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
   ROOT_PASSWORD: MTIzNDU=
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-mysql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/app/data/mysql" #nodepath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: task-pv-volume-mysql
          persistentVolumeClaim:
            claimName: task-pv-claim-mysql
      containers:
        - name: mysql
          image: mysql:8
          volumeMounts:
            - mountPath: "/var/lib/mysql" #containerpath
              name: task-pv-volume-mysql
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep 15
                    mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'CREATE DATABASE IF NOT EXISTS keycloak;'
                    mysql -u root -p$MYSQL_ROOT_PASSWORD -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_ROOT_PASSWORD';"
                    mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'CREATE DATABASE IF NOT EXISTS apps_db;'
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ROOT_PASSWORD
                  name: mysecret
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - name: node-port
    port:  3306
    targetPort: 3306
    nodePort: 30505

