apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-configmap
  namespace: default
data:
  default.config: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm index.json;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-json-comfigmap
  namespace: default
data:
  index.html: |
    <html><body><h1>Hello Assad</h1></body></html>    
---

apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx
  labels:
    run: nginx
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c']
    args: 
      - |
        cp /tmp/nginx/default.config /etc/nginx/conf.d/default.config
    volumeMounts:
    - name: nginx-default-config
      mountPath: /etc/nginx/conf.d/
    - name: config
      mountPath: /tmp/nginx/ 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-index-json-config-volume
      mountPath: /usr/share/nginx/html
    - name: nginx-default-config
      mountPath: /etc/nginx/conf.d/ 
  volumes:
    - name: nginx-index-json-config-volume
      configMap:
        name: nginx-index-json-comfigmap
    - name: nginx-default-config
      emptyDir: {}
    - name: config
      configMap:
        name: nginx-default-configmap 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    run: nginx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort    
  selector:
    run: nginx        
