kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-env-pod-editor-cr
rules:
- apiGroups:
  - ''
  - batch
  resources:
  - pods
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
