kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-env-pod-editor-cr
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-env-pod-editor-rb
  namespace: test-env
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-env-pod-editor-cr
subjects:
- kind: ServiceAccount
  name: k8s-dashboard-viewer
  namespace: kubernetes-dashboard

# Follow following example
# https://medium.com/faun/kubernetes-rbac-use-one-role-in-multiple-namespaces-d1d08bb08286
