kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-viewonly
  
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - bindings
      - componentstatuses
      - configmaps
      - endpoints
      - events
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - pods/log
      - pods/exec
      - podtemplates
      - replicationcontrollers
      - resourcequotas
      - serviceaccounts
      - services
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - '*'
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
