apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-env
  name: test-env-secret-reader-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-env-secret-reader-rb
  namespace: test-env
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-env-secret-reader-role
subjects:
- kind: ServiceAccount
  name: k8s-dashboard-viewer
  namespace: kubernetes-dashboard
